# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: N2MzZDAzODM3NDM0MmVhYjQ4NzI1YjMxN2JmM2U5ZDcyOGVlYWUzN2EwZGQ5YTBjYTYyNDJmMGMxNzQ0NGM0MzYwZmUyYmI1NTUxOTViZDgwMTVjNTM0MzZhNDkwY2IwOGVmOTI4NDAwNjU4Mzc3YjljYmNkZjlmZTRiNTQ1Zjg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
